name: "Setup Node"
description: "Setup Node.js"
inputs:
  node-version:
    description: "The version of Node.js to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: git checkout
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: pnpm/action-setup@v4

    # This enables task distribution via Nx Cloud
    # Run this command as early as possible, before dependencies are installed
    # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
    # Connect your workspace by running "nx connect" and uncomment this
    # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
