name: Check do not merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  ok-to-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
      - uses: ./modules/ci/do-not-merge
        with:
          labels: ${{ toJson(github.event.pull_request.labels.*.name) }}
